name: mir-kiosk-neverputt
adopt-info: neverputt
summary: neverputt packaged as a mir-kiosk snap
description: neverputt packaged as a mir-kiosk snap
confinement: strict
grade: stable
base: core20
license: GPL-2.0

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

environment:
  # ${SNAPCRAFT_ARCH_TRIPLET} doesn't play nice with layout
  LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pulseaudio
  # Prep EGL
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d
  LIBGL_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
  LIBVA_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
  # Prep SDL
  SDL_VIDEODRIVER: wayland

layout:
  /usr/share:
    bind: $SNAP/usr/share
  /usr/games:
    bind: $SNAP/usr/games

plugs:
  wayland:
  opengl:
  audio-playback:
  alsa:
  hardware-observe: # This allows some UDEV access neverputt wants

apps:
  daemon:
    command-chain:
      - bin/run-daemon
      - bin/wayland-launch
    command: usr/games/neverputt
    daemon: simple
    restart-condition: always
    environment:
      # Prep PulseAudio
      PULSE_SYSTEM: 1
      PULSE_RUNTIME_PATH: /var/run/pulse

  mir-kiosk-neverputt:
    command-chain:
      - bin/wayland-launch
    command: usr/games/neverputt
    desktop: usr/share/applications/neverputt.desktop
    environment:
      # Prep PulseAudio
      PULSE_SERVER: unix:$XDG_RUNTIME_DIR/../pulse/native

parts:
  neverputt:
    plugin: nil
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version `LANG=C apt-cache policy neverputt | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/\1/p'`
    override-build: |
      snapcraftctl build
      sed -i s:Icon=neverputt:Icon=/usr/share/games/neverball/icon/neverputt.png:g $SNAPCRAFT_PART_INSTALL/usr/share/applications/neverputt.desktop
    stage-packages:
      - neverputt

  config:
    plugin: dump
    source: config

  mir-kiosk-snap-launch:
    plugin: dump
    source: https://github.com/MirServer/mir-kiosk-snap-launch.git
    override-build:  $SNAPCRAFT_PART_BUILD/build-with-plugs.sh opengl audio-playback alsa wayland hardware-observe
    stage-packages:
     - inotify-tools

  sdl2:
    plugin: nil
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libsdl2-mixer-2.0-0
      - libsdl2-net-2.0-0

  mesa:
    plugin: nil
    stage-packages:
      - libgl1-mesa-dri
      - libwayland-egl1-mesa
      - libglu1-mesa

  wayland:
    plugin: nil
    stage-packages:
      - libwayland-client0
